//! Integración con el servidor de sonido del sistema (PipeWire / PulseAudio).
//!
//! Agrupa la detección del servidor, la aplicación en vivo del reloj del gráfico
//! (force-rate / force-quantum de PipeWire), la persistencia de los archivos de
//! configuración (`pipewire.conf.d` / `daemon.conf`) y la consulta de estado.
//! La GUI solo llama a estas funciones; el motor de audio no depende de ellas.

/// Verifica si PipeWire está activo como servicio de usuario.
pub fn is_pipewire_active() -> bool {
    let check_pw = std::process::Command::new("systemctl")
        .args(["--user", "is-active", "pipewire"])
        .output();
    match check_pw {
        Ok(out) => String::from_utf8_lossy(&out.stdout).trim() == "active",
        Err(_) => false,
    }
}

/// Aplica el reloj del gráfico de PipeWire en caliente (force-rate y force-quantum).
///
/// Debe ejecutarse ANTES de construir el stream de salida: si se aplica después,
/// PipeWire reconfigura el grafo y el stream existente queda desconectado del sink
/// (su callback sigue drenando el ringbuf pero el audio no llega al dispositivo).
pub fn apply_pipewire_clock(rate: Option<u32>, quantum: Option<u32>) {
    let rate_str = rate
        .map(|r| r.to_string())
        .unwrap_or_else(|| "0".to_string());
    let quantum_str = quantum
        .map(|q| q.to_string())
        .unwrap_or_else(|| "0".to_string());

    let _ = std::process::Command::new("pw-metadata")
        .args(["-n", "settings", "0", "clock.force-rate", &rate_str])
        .status();
    let _ = std::process::Command::new("pw-metadata")
        .args(["-n", "settings", "0", "clock.force-quantum", &quantum_str])
        .status();
}

/// Persiste la configuración del reloj en `~/.config/pipewire/pipewire.conf.d/audoxidy.conf`.
///
/// Si `rate` y `quantum` son `None`, elimina el archivo (restaura el valor por defecto).
pub fn persist_pipewire_conf(rate: Option<u32>, quantum: Option<u32>) {
    if let Ok(home) = std::env::var("HOME") {
        let dir_path = format!("{}/.config/pipewire/pipewire.conf.d", home);
        let file_path = format!("{}/audoxidy.conf", dir_path);

        if rate.is_none() && quantum.is_none() {
            let _ = std::fs::remove_file(&file_path);
            return;
        }
        if let Err(e) = std::fs::create_dir_all(&dir_path) {
            tracing::warn!("No se pudo crear el directorio {}: {}", dir_path, e);
        }

        let mut content = String::new();
        content.push_str("context.properties = {\n");
        if let Some(r) = rate {
            content.push_str(&format!("    default.clock.rate = {}\n", r));
            content.push_str(&format!("    default.clock.allowed-rates = [ {} ]\n", r));
        }
        if let Some(q) = quantum {
            content.push_str(&format!("    default.clock.quantum = {}\n", q));
        }
        content.push_str("}\n");
        if let Err(e) = std::fs::write(&file_path, content) {
            tracing::warn!("No se pudo escribir {}: {}", file_path, e);
        }
    }
}

/// Persiste la configuración en `~/.config/pulse/daemon.conf` (fallback sin PipeWire).
///
/// PulseAudio no tiene un comando en vivo equivalente a `pw-metadata`; el archivo
/// aplica al reiniciar el servicio y PulseAudio resamplea el stream a la tasa del
/// sink de forma transparente.
pub fn persist_pulse_conf(rate: Option<u32>, quantum: Option<u32>) {
    if let Ok(home) = std::env::var("HOME") {
        let dir_path = format!("{}/.config/pulse", home);
        let file_path = format!("{}/daemon.conf", dir_path);

        let mut lines = Vec::new();
        if std::path::Path::new(&file_path).exists() {
            if let Ok(file_content) = std::fs::read_to_string(&file_path) {
                for line in file_content.lines() {
                    let trimmed = line.trim();
                    if trimmed.starts_with("default-sample-rate")
                        || trimmed.starts_with("alternate-sample-rate")
                        || trimmed.starts_with("default-fragments")
                        || trimmed.starts_with("default-fragment-size-msec")
                        || trimmed.starts_with("; Generated by Audoxidy")
                    {
                        continue;
                    }
                    lines.push(line.to_string());
                }
            }
        } else {
            if let Err(e) = std::fs::create_dir_all(&dir_path) {
                tracing::warn!("No se pudo crear el directorio {}: {}", dir_path, e);
            }
        }

        if rate.is_some() || quantum.is_some() {
            lines.push("; Generated by Audoxidy".to_string());
            if let Some(r) = rate {
                lines.push(format!("default-sample-rate = {}", r));
                lines.push(format!("alternate-sample-rate = {}", r));
            }
            if let Some(q) = quantum {
                let r = rate.unwrap_or(48000);
                let msec = ((q as f64 / r as f64) * 1000.0 / 2.0).max(1.0) as u32;
                lines.push("default-fragments = 2".to_string());
                lines.push(format!("default-fragment-size-msec = {}", msec));
            }
        }

        if let Err(e) = std::fs::write(&file_path, lines.join("\n") + "\n") {
            tracing::warn!("No se pudo escribir {}: {}", file_path, e);
        }
    }
}

/// Reinicia los servicios de audio del sistema (PipeWire + WirePlumber).
pub fn restart_audio_services() {
    let _ = std::process::Command::new("systemctl")
        .args([
            "--user",
            "restart",
            "pipewire.service",
            "pipewire-pulse.service",
            "wireplumber.service",
        ])
        .status();
}

/// Devuelve el estado actual del servidor de sonido del sistema.
///
/// Con PipeWire lee la tasa/quantum activos (teniendo en cuenta los valores
/// forzados) vía `pw-metadata`; con PulseAudio lee la especificación de muestra
/// vía `pactl` y el quantum desde `daemon.conf`. Devuelve `(estado, latencia)`.
pub fn system_sound_status() -> (String, String) {
    let has_pw = is_pipewire_active();

    if has_pw {
        // Frecuencia y quantum del servidor PipeWire actual (y sus valores forzados).
        let mut sys_rate = None;
        let mut sys_force_rate = None;
        let mut sys_quantum = None;
        let mut sys_force_quantum = None;

        if let Ok(output) = std::process::Command::new("pw-metadata")
            .args(["-n", "settings"])
            .output()
        {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                let extract_value = |line_str: &str| -> Option<String> {
                    if let Some(pos) = line_str.find("value:'") {
                        let start = pos + 7;
                        if let Some(end) = line_str[start..].find("'") {
                            return Some(line_str[start..start + end].to_string());
                        }
                    }
                    None
                };

                if line.contains("clock.rate") {
                    if let Some(val) = extract_value(line) {
                        sys_rate = Some(val);
                    }
                } else if line.contains("clock.force-rate") {
                    if let Some(val) = extract_value(line) {
                        sys_force_rate = Some(val);
                    }
                } else if line.contains("clock.quantum") {
                    if let Some(val) = extract_value(line) {
                        sys_quantum = Some(val);
                    }
                } else if line.contains("clock.force-quantum") {
                    if let Some(val) = extract_value(line) {
                        sys_force_quantum = Some(val);
                    }
                }
            }
        }

        let active_sys_rate = if let Some(ref fr) = sys_force_rate {
            if fr != "0" {
                Some(fr.clone())
            } else {
                sys_rate.clone()
            }
        } else {
            sys_rate.clone()
        };

        let active_sys_quantum = if let Some(ref fq) = sys_force_quantum {
            if fq != "0" {
                Some(fq.clone())
            } else {
                sys_quantum.clone()
            }
        } else {
            sys_quantum.clone()
        };

        let status = match (active_sys_rate.clone(), active_sys_quantum.clone()) {
            (Some(r), Some(q)) => format!("{} Hz | {}", r, q),
            (Some(r), None) => format!("{} Hz | --", r),
            (None, Some(q)) => format!("-- | {}", q),
            _ => "--".to_string(),
        };
        let lat = match (active_sys_rate, active_sys_quantum) {
            (Some(r_str), Some(q_str)) => {
                if let (Ok(r), Ok(q)) = (r_str.parse::<f64>(), q_str.parse::<f64>()) {
                    if r > 0.0 {
                        format!("Latencia: {:.2} ms", (q / r) * 1000.0)
                    } else {
                        "Latencia: -- ms".to_string()
                    }
                } else {
                    "Latencia: -- ms".to_string()
                }
            }
            _ => "Latencia: -- ms".to_string(),
        };
        (status, lat)
    } else {
        // PulseAudio: tasa desde `pactl info` y quantum desde `daemon.conf`.
        let mut pulse_rate = None;
        if let Ok(output) = std::process::Command::new("pactl").arg("info").output() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                if line.contains("Default Sample Specification:") {
                    let parts = line.split_whitespace().collect::<Vec<_>>();
                    if let Some(last) = parts.last() {
                        pulse_rate = Some(last.replace("Hz", ""));
                    }
                }
            }
        }

        let mut pulse_quantum = None;
        if let Ok(home) = std::env::var("HOME") {
            let file_path = format!("{}/.config/pulse/daemon.conf", home);
            if let Ok(content) = std::fs::read_to_string(file_path) {
                for line in content.lines() {
                    let trimmed = line.trim();
                    if trimmed.starts_with("default-fragment-size-msec") {
                        if let Some(val) = trimmed.split('=').nth(1) {
                            pulse_quantum = Some(val.trim().to_string());
                        }
                    }
                }
            }
        }

        let status = match (pulse_rate.clone(), pulse_quantum.clone()) {
            (Some(r), Some(q)) => format!("{} Hz | {} ms", r, q),
            (Some(r), None) => format!("{} Hz | --", r),
            (None, Some(q)) => format!("-- | {} ms", q),
            _ => "--".to_string(),
        };
        let lat = if let Some(q) = pulse_quantum {
            if let Ok(q_f) = q.parse::<f64>() {
                format!("Latencia: {:.2} ms", q_f)
            } else {
                format!("Latencia: {} ms", q)
            }
        } else {
            "Latencia: -- ms".to_string()
        };
        (status, lat)
    }
}
